version: "3.3"
services:
  db:
    restart: always
    image: mariadb
    env_file:
      - .db_env
    ports:
      - "3302:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - react_build:/app/frontend/build
    depends_on:
      - backend
  backend:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - db
    entrypoint: /app/backend/wsgi-entrypoint.sh
    expose:
      - 8000
  nginx:
    restart: always
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/rumergy
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
