# Generated by Django 3.2.8 on 2021-11-01 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rumergy', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='justification',
            field=models.CharField(default='No justification provided', max_length=200),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='ocupation',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
