# Generated by Django 3.2.9 on 2021-11-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0002_auto_20211107_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='comments',
            field=models.CharField(default='No comment provided', max_length=200),
        ),
    ]
