# Generated by Django 3.2.8 on 2021-11-02 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rumergy', '0003_auto_20211101_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
