# Generated by Django 3.2.8 on 2021-11-01 22:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0003_auto_20211101_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('start_address', models.PositiveSmallIntegerField()),
                ('end_address', models.PositiveSmallIntegerField()),
                ('data_type', models.CharField(choices=[('INT', 'Integer'), ('FLT', 'Float')], default='FLT', max_length=3)),
                ('register_type', models.CharField(choices=[('COIL', 'Coil'), ('DISC', 'Discrete Input'), ('INPU', 'Input Register'), ('HOLD', 'Holding Register')], default='HOLD', max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='datalog',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datalog',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datalog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_logs', to='rumergy.userprofile'),
        ),
    ]
