# Generated by Django 3.2.8 on 2021-11-03 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rumergy', '0003_auto_20211101_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('port', models.IntegerField(default=502)),
                ('substation', models.CharField(max_length=60)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('comments', models.CharField(max_length=200)),
                ('panel_id', models.CharField(max_length=60)),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], default='ACT', max_length=3)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meters', to='rumergy.building')),
            ],
        ),
        migrations.CreateModel(
            name='MeterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avg', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_data', to='rumergy.meter')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meters', to='rumergy.metermodel'),
        ),
        migrations.CreateModel(
            name='DataLogMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_log', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='data_log_measures', to='rumergy.datalog')),
            ],
        ),
    ]
