# Generated by Django 3.2.9 on 2021-11-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0004_auto_20211102_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrequest',
            old_name='ocupation',
            new_name='occupation',
        ),
    ]
