# Generated by Django 3.2.9 on 2021-11-11 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0006_alter_meterdata_data_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='ip',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metermodel',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='selecteddatapoint',
            name='data_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points_selected', to='rumergy.datalog'),
        ),
        migrations.AddField(
            model_name='selecteddatapoint',
            name='data_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='data_points_selected', to='rumergy.datapoint'),
        ),
    ]
