# Generated by Django 3.2.9 on 2021-11-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0006_alter_meterdata_data_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='data_points',
            field=models.ManyToManyField(related_name='data_logs', to='rumergy.DataPoint'),
        ),
    ]
