# Generated by Django 3.2.9 on 2021-11-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0007_datalog_data_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('ERR', 'Error')], default='ACT', max_length=3),
        ),
    ]
