# Generated by Django 3.2.9 on 2021-11-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0008_datapoint_unique data point name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedDataPoint',
        ),
    ]
