# Generated by Django 3.2.9 on 2021-11-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0007_datalog_data_points'),
        ('rumergy', '0009_delete_selecteddatapoint'),
    ]

    operations = [
    ]
