# Generated by Django 3.2.9 on 2021-11-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0011_datalog_sampling_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='ip',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('ip', 'port'), name='unique meter IP'),
        ),
    ]
