# Generated by Django 3.2.9 on 2021-11-22 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0008_alter_meter_status'),
        ('rumergy', '0011_datalog_sampling_rate'),
    ]

    operations = [
    ]
