# Generated by Django 3.2.9 on 2021-12-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0012_auto_20211122_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('ERR', 'Error')], default='ACT', max_length=3),
        ),
    ]
