# Generated by Django 3.2.9 on 2021-12-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0012_auto_20211122_1546'),
        ('rumergy', '0012_merge_20211122_0148'),
    ]

    operations = [
    ]
