# Generated by Django 3.2.9 on 2021-12-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0013_auto_20211204_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
