# Generated by Django 3.2.9 on 2021-12-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0013_alter_meter_status'),
        ('rumergy', '0014_alter_meter_serial_number'),
    ]

    operations = [
    ]
