# Generated by Django 4.0 on 2021-12-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rumergy', '0015_merge_20211206_2002'),
        ('rumergy', '0016_datalogmeasures_status'),
    ]

    operations = [
    ]
